applications:
  _core:
    argocd:
      deploy: true
      autoSync: false
      namespace: argocd
    certManager:
      deploy: true
      autoSync: true
    externalDns:
      deploy: true
      autoSync: true
    ingressNginx:
      deploy: true
      autoSync: true
    metallb:
      deploy: true
      autoSync: true
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: "CustomResourceDefinition"
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
    sealedSecrets:
      deploy: true
      autoSync: true
  authentik:
    deploy: false
    autoSync: true
  cilium:
    deploy: true
    autoSync: false
    namespace: kube-system
  grafana:
    deploy: true
    autoSync: true
  grafanaDashboards:
    deploy: true
    autoSync: true
    namespace: grafana
    serverSideApply: true
  homeAssistant:
    deploy: false
    autoSync: true
  intelDevicePluginsGpu:
    deploy: true
    ignoreDifferences:
      - group: "deviceplugin.intel.com"
        kind: "GpuDevicePlugin"
        jsonPointers:
          - /spec/resourceManager
  jenkins:
    deploy: false
    autoSync: true
  kepler:
    deploy: false
    autoSync: true
  keycloakx:
    deploy: true
    autoSync: false
  loki:
    deploy: true
    autoSync: true
  longhorn:
    deploy: true
    autoSync: false
    namespace: longhorn-system
  metricsServer:
    deploy: true
    autoSync: true
  minio:
    deploy: true
    autoSync: true
  nextcloud:
    deploy: false
    autoSync: true
  nodeFeatureDiscovery:
    deploy: true
    autoSync: true
  oauth2Proxy:
    deploy: true
    autoSync: true
  postgresql:
    deploy: true
    autoSync: true
  prometheus:
    deploy: true
    autoSync: true
  prometheusCrd:
    deploy: true
    autoSync: true
    namespace: defaults
    serverSideApply: true
  promtail:
    deploy: true
    autoSync: true
  victoriaMetrics:
    deploy: false
    autoSync: true
    serverSideApply: true
  vpa:
    deploy: true
    autoSync: true
