applications:
  core:
    argocd:
      deploy: true
      autoSync: false
      namespace: argocd
    cert-manager:
      deploy: true
      autoSync: true
    cilium:
      deploy: true
      autoSync: false
      namespace: kube-system
    external-dns:
      deploy: true
      autoSync: true
    ingress-nginx:
      deploy: true
      autoSync: true
    metallb:
      deploy: true
      autoSync: true
      ignoreDifferences:
        - group: "apiextensions.k8s.io"
          kind: "CustomResourceDefinition"
          jsonPointers:
            - /spec/conversion/webhook/clientConfig/caBundle
    sealed-secrets:
      deploy: true
      autoSync: true
      namespace: kube-system
    vpa:
      deploy: true
      autoSync: true
  devices:
    intel-device-plugins-gpu:
      deploy: true
      ignoreDifferences:
        - group: "deviceplugin.intel.com"
          kind: "GpuDevicePlugin"
          jsonPointers:
            - /spec/resourceManager
    node-feature-discovery:
      deploy: true
      autoSync: true
  home:
    home-assistant:
      deploy: false
      autoSync: true
    nextcloud:
      deploy: false
      autoSync: true
  media:

  monitoring:
    grafana:
      deploy: true
      autoSync: true
    grafana-dashboards:
      deploy: true
      autoSync: true
      namespace: grafana
      serverSideApply: true
    kepler:
      deploy: false
      autoSync: true
    loki:
      deploy: true
      autoSync: true
    metrics-server:
      deploy: true
      autoSync: true
    prometheus:
      deploy: true
      autoSync: true
    prometheus-crd:
      deploy: true
      autoSync: true
      namespace: defaults
      serverSideApply: true
    promtail:
      deploy: true
      autoSync: true
  storage:
    longhorn:
      deploy: true
      autoSync: false
      namespace: longhorn-system
    minio:
      deploy: true
      autoSync: true
    postgresql:
      deploy: true
      autoSync: true
  other:
    authentik:
      deploy: false
      autoSync: true
    keycloakx:
      deploy: true
      autoSync: false
    oauth2-proxy:
      deploy: true
      autoSync: true
    victoria-metrics:
      deploy: false
      autoSync: true
      serverSideApply: true
